### ISSUE TITLE
Suggestion for additional features

### ISSUE THREAD

**Issue by uspoma** [dfrits/MobilePauker2#1]
Hello,

thanks for bringing this app to android. Tried it and I like it. Now I have a few comments and I would like to hear your opinion on them.

a) As of now when you start a learning session you have to click through all the cards first before the 'SHOW ME!' button comes. Would it be possible to make a simple cram option where you can instantly start without clicking through all the cards? I mean basically an option to skip that first part to have to click through all of them before the learning can start?

b) Do you plan to implement a mechanism for importing sets (Ankidroid has an import feature for example)? I have lots of lists but at the moment it seems impossible to get them into the app.

Those two additional features would make add lots of usability.

Thanks for considering.

**Comment by dfrits** [comment]
Hello uspoma,

sry for the late response and thank you for the interest.

These are interesting suggestions there.
a) I don't know if I understood that right. But the learning proccess is the same as from the PC-Version named "[Pauker](http://pauker.sourceforge.net)". So you learn the words in the time you set in the settings and after that time you repeat them.

b) The PC-Version has a feature like that and I am thinking about to bring this to the mobile version too.

I hope I answered your questions well.

Daniel
