### ISSUE TITLE
Unable to install V,2.0.1

### ISSUE THREAD

**Issue by darewealth** [dfrits/MobilePauker2#6]
### Describe the bug.

I was unable to install  the version 2.0.1. Whenever I try it shows error parsing the package.

### Steps to reproduce.

* Download and install 

### Screenshot
![Screenshot_20190518-101510](https://user-images.githubusercontent.com/36304257/57967413-7fd00b80-7956-11e9-86b5-9b980f46b9f7.png)

### Devices and Versions)

* Device: [Gionee]

* Version [7.0]

* App version [2.0.1]

**Comment by dfrits** [comment]
Please try this out [Parser problem fix](https://www.imobie.com/support/fix-problem-of-parsing-the-package.htm). Tell if it still appears.

**Comment by darewealth** [comment]
Yes, I've tried the [parser problem fix](https://www.imobie.com/support/fix-problem-of-parsing-the-package.htm), the problem still persist. I think I should be able to download if upgraded back to android 7.
