### ISSUE TITLE
Deleting a card crashes the app

### ISSUE THREAD

**Issue by crysports** [dfrits/MobilePauker2#7]
I added a few cards by clicking on add card.
Then I clicked on learn and played with it for sometime.
I tried to delete the card but app hung for a while and finally crashed.
Here is a video recording

https://youtu.be/ezVQQQVCGvU

**Comment by dfrits** [comment]
If you restart the there should come a dialog to send the error. Please send me this if it happens again, because that helps alot.

I will look for that error and fix it. Thank you

**Comment by crysports** [comment]
Report sent.

**Comment by dfrits** [comment]
thank you. 

I was able to reproduce it and found and fixed the problem. I will soon upload the bugfix.
