### ISSUE TITLE
[Feature Request] Folders

### ISSUE THREAD

**Issue by RubenKelevra** [dfrits/MobilePauker2#8]
I just found your app on F-Droid and was pleasently surprised by its quality, thank you for bringing Pauker to Android.

I found some small stuff which I think can be improved, so I'll create some tickets to share this ideas with you.

---

Currently your App don't read any folders in it's Dropbox-Folder. I'm not sure if it's possible to implement that with the Dropbox API, but it would be a great addition. I'm using Pauker for a lot of different stuff, so it's the easiest to organize that with folders instead of filename-prefixes.

![Screenshot_20191004-100552__01](https://user-images.githubusercontent.com/614929/66192071-ffedd800-e68f-11e9-9499-e26d43a64b8d.jpg)

**Comment by dfrits** [comment]
Sorry for the very late response, I never checked my Issues.

I didn't have the time to implement that feature in my master project. But I put it on my TODO-list.
