### ISSUE TITLE
[Bug] Wrong description on Repeat-Exit

### ISSUE THREAD

**Issue by RubenKelevra** [dfrits/MobilePauker2#9]
The App shows a dialogue when you press back while repeating cards. IMHO the dialogue itself is pretty unnecessary, since you don't loose anything, if you take a break from repeating cards. But, if you think this dialogue is important: It's currently labeled with "Exit Learning", while you actually are repeating.

**Comment by dfrits** [comment]
Sry for my very late reply. 

You are right. If you take very accurate, it should be named "Exit Repeating". But I thought at the time I implemented that, that it doesn't matter so much and time was short to finish. I think i correct it next time.

I think the dialog is not unnecessary. For me it happenes sometimes, that I press accidently the Back Button and then stop the repeating. You are right, nothing happens, but I think it is not bad.

**Comment by dfrits** [comment]
Sry for my very late reply. 

You are right. If you take very accurate, it should be named "Exit Repeating". But I thought at the time I implemented that, that it doesn't matter so much and time was short to finish. I think i correct it next time.

I think the dialog is not unnecessary. For me it happenes sometimes, that I press accidently the Back Button and then stop the repeating. You are right, nothing happens, but I think it is not bad.

**Comment by dfrits** [comment]
Sry for my very late reply. 

You are right. If you take very accurate, it should be named "Exit Repeating". But I thought at the time I implemented that, that it doesn't matter so much and time was short to finish. I think i correct it next time.

I think the dialog is not unnecessary. For me it happenes sometimes, that I press accidently the Back Button and then stop the repeating. You are right, nothing happens, but I think it is not bad.

**Comment by dfrits** [comment]
Sry for my very late reply. 

You are right. If you take very accurate, it should be named "Exit Repeating". But I thought at the time I implemented that, that it doesn't matter so much and time was short to finish. I think i correct it next time.

I think the dialog is not unnecessary. For me it happenes sometimes, that I press accidently the Back Button and then stop the repeating. You are right, nothing happens, but I think it is not bad.

**Comment by dfrits** [comment]
Sry for my very late reply. 

You are right. If you take very accurate, it should be named "Exit Repeating". But I thought at the time I implemented that, that it doesn't matter so much and time was short to finish. I think i correct it next time.

I think the dialog is not unnecessary. For me it happenes sometimes, that I press accidently the Back Button and then stop the repeating. You are right, nothing happens, but I think it is not bad.

**Comment by dfrits** [comment]
Sry for my very late reply.

**Comment by dfrits** [comment]
Sry for my very late reply.

**Comment by dfrits** [comment]
Sry for my very late reply.

**Comment by dfrits** [comment]
Sry for my very late reply.

**Comment by dfrits** [comment]
Sry for my very late reply.

**Comment by dfrits** [comment]
Sry for my very late reply.

**Comment by dfrits** [comment]
Sry for my very late reply.
